apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hyunsu-applications
  namespace: argocd
  labels:
    layer: applications
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'monero-miner'
      labels:
        layer: environment
    spec:
      project: hyunsu-applicaition
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      source:
        path: charts/monero-miner
        repoURL: https://github.com/Hyunsu-Playground/hyunsu-gitops-repo.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Createnamespace=true
          - "--creds=argocd-ecr-secret"