apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monero-miner
  namespace: xmrig
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: xmrig
    name: in-cluster
  project: hyunsu-application
  source:
    path: charts/monero-miner
    repoURL: https://github.com/Hyunsu-Playground/hyunsu-gitops-repo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true